# Generated by Django 2.2.4 on 2019-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('t1', 'type 1'), ('t2', 'type 2'), ('t3', 'type 3')], max_length=2),
        ),
    ]
