# Generated by Django 2.2.4 on 2019-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190828_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default='Default tag', max_length=100),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
