# Generated by Django 2.2.4 on 2019-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190828_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
